### PR TITLE
Create sketch library for sso component

### PR DESCRIPTION
**Pull request by nellem23**
New Sketch library and symbols for the Product Design team to use the SSO menu component to navigate & authenticate to Atlas, Support, University, the Account app, or log out (of all apps).

Cover

Screen Shot 2019-07-17 at 3 29 16 PM

Atlas

### CODE REVIEW

**Review by fredtruman — CHANGES_REQUESTED** [review]
Amazing @nellem23 ! This is a tricky one since it's both one of the more complex library files we've made, and also very specific to the instances of use. Because of that specificity, my questions are mostly targeted at how we can provide the minimum amount of customization for this symbol to work for its intended use (i.e. let's restrict this symbol's use as much as possible):


- Just want to confirm how many symbol instances we need to provide: 3 (ATLAS active, UNIVERSITY active, SUPPORT active) or 4 (the previous + a NONE option) Will we ever see the SSO Menu outside of these three contexts (Atlas, University, Support)? I'm thinking of Charts for example: would opening the SSO menu from Charts show an active Atlas item, or no active item?


- Next, curious if the SSO Menu will ever appear in any other context outside of those (either 3 or 4) above? If the answer NO, I would suggest that our library file consist of ONLY those (either 3 or 4) instances without options to override the nav items with specific text or active. We probably just want to provide the ability to override the username and email and that's it. 


- The only caveat to the above comment is that of course we do want to include the dropdown as well since its unique to this component, though it currently scales kind of awkwardly if I want to include a different name.
Screenshot 2019-07-17 15 38 45


- I would also consider locking everything in each instance of the menu so that it cannot be resized (unless there will be a need for that in which case I would also just ensure it scales elegantly)
Screenshot 2019-07-17 16 05 18


- "Universal SSO Component" feels a little long for the name. Thoughts on naming it just "SSO Menu"?
Screenshot 2019-07-17 15 34 12


- Last nitpick :D can you resave the file, and when you have the title page visible so it shows in Finder / Sketch preferences? (makes it easier to see)
Screenshot 2019-07-17 15 31 39

**Comment by nellem23** [comment]
@fredtruman 

_- Just want to confirm how many symbol instances we need to provide: 3 (ATLAS active, UNIVERSITY active, SUPPORT active) or 4 (the previous + a NONE option) Will we ever see the SSO Menu outside of these three contexts (Atlas, University, Support)? I'm thinking of Charts for example: would opening the SSO menu from Charts show an active Atlas item, or no active item?_
- As of right now I think it makes sense to just show the 3 contexts so I'll remove the NONE option. With Charts, we did consider when the SSO project was underway whether or not to include Charts as an option, and the decision was to exclude it for now. Because of the future Cloud IA/SRFC stuff we didn't want to add a nav item that might disappear in the future, and we wanted want to treat Stitch and Charts as embedded products in Atlas.

_- Next, curious if the SSO Menu will ever appear in any other context outside of those (either 3 or 4) above? If the answer NO, I would suggest that our library file consist of ONLY those (either 3 or 4) instances without options to override the nav items with specific text or active. We probably just want to provide the ability to override the username and email and that's it._

- For right now I only expect to have the SSO Menu appear in those 3 contexts. I haven't figured out how to setup text overrides in Sketch but I'm excited to figure this out and will do some googling! 

_- The only caveat to the above comment is that of course we do want to include the dropdown as well since its unique to this component, though it currently scales kind of awkwardly if I want to include a different name._

- Ah this is a good catch. Just thinking about this again, do you think it makes sense to combine the dropdown + menu so that we have the following symbols: Dropdown, Dropdown + Menu (ATLAS), Dropdown + Menu (UNIVERSITY), Dropdown + Menu (SUPPORT) so that people don't have to think about the spacing of these elements? 

_- I would also consider locking everything in each instance of the menu so that it cannot be resized (unless there will be a need for that in which case I would also just ensure it scales elegantly)_

- Yep that makes sense to me! The only case I can think of, is that if the user's name is long then the menu's width should scale.  

_-"Universal SSO Component" feels a little long for the name. Thoughts on naming it just "SSO Menu"_

- I went back and forth on the name and agree it feels to long. I wanted to communicate that this menu will be in all of our web products but didn't find any names that I like. I worried that not all designers will know what SSO Menu is... I'll keep thinking on it. 

_-Last nitpick :D can you resave the file, and when you have the title page visible so it shows in Finder / Sketch preferences? (makes it easier to see)_

- I always wondered how ya'll made those covers on your libraries appear! Yep I will fix this.

**Comment by nellem23** [comment]
@fredtruman Made the changes based on your feedback.

The outstanding piece I haven't address is the name of the library :/

**Comment by fredtruman** [comment]
Thanks @nellem23 - It's looking good! Don't kill me, but a couple more thoughts:

- I don't think we need the reference page. Since library files aren't really intended to be opened by a designer ever, its symbols are just used through the symbol menu system. This kind of documentation should be provided in the "design guidelines" (I shared a blank google document with you that lives in our design systems team drive) and published to mongodb.design (eventually).
Screenshot 2019-07-18 17 27 21


- Challenge: To reduce the complexity of the file I think the entire library file could have 6 symbols total:
1. dropdown
2. Atlas
3. Support
4. University
5. Menu Item
6. Menu Item Active
This would require creating generic Menu Item and Menu Item Active, using them in each of the Atlas, Support, University menus and using their overrides in the menu. 
Screenshot 2019-07-18 17 32 15

Then, in each instance of the menu (Atlas, University, Support) you can disallow those menu items from being overridden, see this screenshot:
Screenshot 2019-07-18 17 25 25


- To make the dropdown portion easier to size, you can pin the left side of the text input and make it fixed width to enforce it to wrap if there is too much text. This would tell the designer: "shrink the dropdown just enough so that the text doesn't wrap and then the padding is perfect"
Screenshot 2019-07-18 17 27 04

- Thoughts on bundling the dropdown with the menus: not sure, but this would make it harder to use a custom name in the dropdown and to be able to resize the dropdown to fit wider names. You'd end up trying to resize the dropdown by resizing the entire menu symbol which might be weird? Maybe though, we could put a small gray hit area that guides where to put the dropdown, like this:
Screenshot 2019-07-18 17 38 11

**Comment by DesignerDave** [comment]
Hey Nelle, thanks for putting this together!

I wanna weigh in and say that I think that we should probably only have the menu bundled with the toggle. I can't imagine that you would want the menu standalone, and we should ensure consistency in the spacing when designers use the symbol.

Since the menu is a fixed width, you could lock its width and keep the toggle dynamic, and pinned to the right side. Additionally, if you make the art board sized to the toggle and have the menu overflow, it can allow for pretty good isolated manipulation of the toggle while maintaining menu size, placement, and spacing. [Screen recording of this behavior.](https://drive.google.com/file/d/1boAVK5YjfHgPQUvjMB24pWPB6epyTI8M/view?usp=sharing)

Notes on a few of the above points:

#### I think the ideal set of symbols for this would be:
- Toggle
- Menu
- Menu + Toggle / Atlas
- Menu + Toggle / Support
- Menu + Toggle / University
- Menu Item / Inactive
- Menu Item / Active

#### I agree with Fred that we don't need an entire mocked-up page for this component.

The extra symbols is quite a bit of clutter for not a lot of payoff IMO. If you look at the other library files, the reference is usually just that component on its own, and is primarily used for QC and when updating.

#### The behavior for long names isn't well defined in the component itself.

We should talk more about whether long names should increase the width of the entire menu, wrap to the next line, or be truncated. There's arguments for each. My worry with having the menu's width adjust is that it will begin to look ridiculous should someone have a more extreme length to their name.

#### My vote is also for the name, "SSO Menu".

Most of the symbol library files in this repo will be used across all of our web products, so that's an unimportant distinction to make here. Is your worry that some designers may not understand "SSO"? What does Google call theirs?

**Comment by fredtruman** [comment]
Oh that's a nice solution @DesignerDave for variable sizing of, and packaging the toggle with the menu.

**Comment by DesignerDave** [comment]
@nellem23 Just checking in on this – any progress?

**Comment by nellem23** [comment]
@Dave McCarter <dave.mccarter@mongodb.com> and @Fred Truman
<fred.truman@10gen.com>

So this has been in my backlog for a while now and I've been finding it
hard to find the time to do this, as you both understand other items have
taken a higher priority. With that said, how would you two like to proceed
with this? @Dave McCarter <dave.mccarter@mongodb.com> it seemed like you
had a clear idea of the changes to make in the sketch library per your
comment on the PR.

*{* name     : "Nelle McDade",
  title    : "Product Designer",
  location : "New York, NY",
  twitter  : "@MongoDB
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2Fmongodb&sa=D&sntz=1&usg=AFQjCNGEAIAhZyZhF7Z9ORWsRliTuc-2dg>
",
  facebook : "MongoDB
<https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2Fmongodb&sa=D&sntz=1&usg=AFQjCNGPMcaFBzmWsh-MpaWeTH6vMQoDIg>
" *}*

**Comment by DesignerDave** [comment]
I figured that might be the case. I can definitely tackle this – just wanted to make sure it doesn't get lost! I'll grab the Jira ticket then.

**Comment by nellem23** [comment]
Thank you so much Dave

*{* name     : "Nelle McDade",
  title    : "Product Designer",
  location : "New York, NY",
  twitter  : "@MongoDB
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2Fmongodb&sa=D&sntz=1&usg=AFQjCNGEAIAhZyZhF7Z9ORWsRliTuc-2dg>
",
  facebook : "MongoDB
<https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2Fmongodb&sa=D&sntz=1&usg=AFQjCNGPMcaFBzmWsh-MpaWeTH6vMQoDIg>
" *}*

**Comment by audroue** [comment]
Hey hey!

I've reviewed the Sketch file and here's what I saw —
- looks like there's a 1px space on the symbol "menu item / university / active"
- looks like there's a 1px space below the "toggle + menu" toggle 
- some colors are not part of the palette, specifically "menu item" titles
- can we be consistent in our naming of our pages? with "Cover", "Reference", "Symbols" (in that order)
- there are 2 oranges for the tooltips in the reference page

**Review by audroue — DISMISSED** [review]
Looks great! 🥂

**Comment by fredtruman** [comment]
Nice overall LGTM, and the menu solution is nice in that the baked-in versions are restricted but I can add in a `base` menu item and override those text elements.

I don't want to suggest over-engineering the sketch solution, however the way text behaves makes me wonder if some will try to detach the symbol in order to get the library to what they want it to. Some thoughts:
- Think the toggle could wrap or clip the username as it exceeds the width. This could help the designer enforce the correct padding on the left of the toggle. As it is now, I have to eyeball that padding since the text just overflows
- Similarly the username and email address in the main user profile could clip (or wrap) with the right-side padding enforced. As is now, the text clips at the edge of the menu element, so I'd have to remove characters and eyeball where the padding would be. Begs the question though if the behavior of this portion of the menu should allow for wrapping usernames? Probably makes sense for the email to clip or truncate in the middle? Middle truncation would allow the @email.com to always be visible (hard in sketch but could be useful in implementation)
- Along the same lines, do we want to allow for multi-line menu-items? multi-line descriptions? If yes we could build that into the sketch library, and if not maybe we just consider clipping that text to one-line (though the padding looks like it is being enforce in the menu items which is great!)

Screenshot 2019-09-06 15 55 49

**Review by fredtruman — DISMISSED** [review]
Left some comments that I think might cause a designer to detach the symbol from the library (which is a library fail) but totally recognize Sketch doesn't allow us to do everything perfectly so happy to move this forward how you see fit @DesignerDave !

cc @audroue

**Comment by DesignerDave** [comment]
So I think I've addressed the issues you had for the most part @fredtruman.

Few notes on your points:
- On truncating email addresses, my inclination is that the email there is usually going to be for verifying which account you're logged into. That said, I think that showing the domain name for the email is far less important than showing the beginning of it. Additionally, it's more clear something is being truncated if it's done at the end. The argument for middle truncation may be that it's less clear that it's an email address if the end is truncated, so there's something to think about...
- I'd currently advocate for maintaining single-line menu item titles and descriptions. Set them to clip for the time being.

**Comment by fredtruman** [comment]
Screenshot 2019-09-06 16 43 22
✨ :shipit: 👍

**Review by fredtruman — APPROVED** [review]

**Pull request merged**
