### PR TITLE
Badge Update

### PR DESCRIPTION
**Pull request by fredtruman**
Leverages new Palette:
Screenshot 2019-05-31 15 42 08

### CODE REVIEW

**Comment by DesignerDave** [comment]
The biggest note I have on this are that the default, heavy, and reverse badges have no border, but our new palette could easily include a border here.

**Comment by fredtruman** [comment]
Yeah, good point @DesignerDave - Here's those with and without borders:
Screenshot 2019-05-31 15 53 59

If we weren't discussing a banner direction that includes borders, I would be inclined to use no borders. But I think it could work either way. If we pursue the bordered-banners (which seems likely) we may want the bordered versions. (Note: heavy banner border is Gray Dark 3)

**Comment by DesignerDave** [comment]
I agree, I'd be inclined to go with the flat version as well if we weren't establishing this pattern for stateful information with banners.

I thin for the default badge, maybe consider light 3 background with the light 2 border? Also, I'm found wondering if we need the reverse badge at all.

Finally, I want to bring up how we name these. I'm not sure I agree with naming by use, rather than by color.

**Comment by fredtruman** [comment]
Here's Light 3 BG and Light 2 border. I think it's ok, though feels too light maybe. Happy to scrap reverse until its use case is established:
Screenshot 2019-05-31 17 05 58

Yeah, naming is interesting. I see it both ways out on other systems, and sometimes mixed (with stateful names mixed with color names, and even just flexible #hex names). Though I think if we're aligning them stylistically with Banners, does it not make sense to align those names to imply the same state? Where I've seen them with just color names assigned the function more like tags:
Elastic (mixed): https://elastic.github.io/eui/#/display/badge
Atlassian a little more function oriented: https://atlassian.design/guidelines/product/components/badges
Priceline (by color): https://pricelinelabs.github.io/design-system/Badge/
IBM (more like a tag): https://www.carbondesignsystem.com/components/tag/code
Quickbooks (more status aligned): https://designsystem.quickbooks.com/component/status-badges/

Depends a little how we're thinking about, and recommending the use of these.

**Comment by fredtruman** [comment]
Hey @DesignerDave have a look:
- Removed REVERSE
- Use color-based naming conventions
- Brought stroke to light and dark grays

Screenshot 2019-06-03 13 24 57
Screenshot 2019-06-03 13 25 57

**Comment by DesignerDave** [comment]
Looks good. Only note – I don't think we need to say "Light" for blue, green, red, or yellow. It seems unnecessary with the variations we have available.

**Comment by fredtruman** [comment]
Good point @DesignerDave RFAL:
- Removed "Light"
- Tried "Gray: Light" and "Gray: Dark" to follow palette pattern ... eh?

Screenshot 2019-06-03 21 20 20
Screenshot 2019-06-03 21 21 34

**Comment by DesignerDave** [comment]
Much better, though I don't see a reason we need to follow the palette convention here, and in fact we probably don't want to imply a 1:1 mapping between the component and colors.

**Comment by fredtruman** [comment]
RFA(final?)L @DesignerDave 😅 

Screenshot 2019-06-05 16 28 36
Screenshot 2019-06-05 16 29 24

**Review by DesignerDave — APPROVED** [review]
I'm happy with this! 😁

**Pull request merged**
