### PR TITLE
Add Cloud IA top navigation to LeafyGreen

### PR DESCRIPTION
**Pull request by DesignerDave**

### CODE REVIEW

**Comment by audroue** [comment]
Hey Dave this is awesome! Here is some feedback. Lmk if you'd like me to quickly update the file if you don't have the bandwidth:

- We can now include the inactive mongo menu button from the symbol library:
image

- shouldn’t mobile still show the user name especially since there’s space?
image

- color for notification icon is different than our red
image

- bell/notification icon is smaller than normal (24px by 24px)
image

- dividing line doesn’t go all the way to the right on desktop
image

- small pixel spacing issue on mobile alignment
image

- charts inactive icon looks smaller then other icons
image

- Should LeafyCorp and Greenery and the MongoMenu Button text be editable?
image

- Should we be able to turn off the notification or edit its value?
image

- update cover to align with others
image

- symbol structure needs reworking and needs to reflect “reference” layer structure
image

**Comment by DesignerDave** [comment]
Hey Rob!

> We can now include the inactive mongo menu button from the symbol library

Sorry, you're right – I don't think I'd updated the symbols since the library update. Should be fixed!

> shouldn’t mobile still show the user name especially since there’s space?

At this point, no – we don't have the time to invest in measuring the user's name programmatically to ensure it fits right now, which is actually a real concern. I'd like to see this updated in the future, but for IA it's set right now.

> color for notification icon is different than our red

Whoops, fixed!

> bell/notification icon is smaller than normal (24px by 24px)

We need to standardize this, but we adjusted the size of all of these to 20x20 because it appeared strange otherwise. The 24x24 icons should be 20x20 actually! 

> dividing line doesn’t go all the way to the right on desktop

Nice catch!

> small pixel spacing issue on mobile alignment

Also nice catch!

> charts inactive icon looks smaller then other icons

Got it, thanks!

> Should LeafyCorp and Greenery and the MongoMenu Button text be editable?

Yep, should be

> Should we be able to turn off the notification or edit its value?

I'm erring on the side of just editing its value for now.

> update cover to align with others

Will do, missed that!

> symbol structure needs reworking and needs to reflect “reference” layer structure

Theres a bunch more states than what's represented on the reference layer. For now, I haven't added a combined Org and Project nav component since the overrides alone would be insane. I cleaned up the structure a bit, but I'm leaning towards keeping it Org Nav / Project Nav at the root of the symbol structure.

**Comment by audroue** [comment]
Heya

> We can now include the inactive mongo menu button from the symbol library

This update isn't showing for me :/ 

> Should LeafyCorp and Greenery and the MongoMenu Button text be editable?

These still don't seem editable.

> Should we be able to turn off the notification or edit its value?

Can't edit it's value 

> update cover to align with others

I don't think the cover changed? 

> Theres a bunch more states than what's represented on the reference layer. For now, I haven't added a combined Org and Project nav component since the overrides alone would be insane. I cleaned up the structure a bit, but I'm leaning towards keeping it Org Nav / Project Nav at the root of the symbol structure.

Why not have the structure be like so, shouldn't be too difficult to order. Don't think any overrides need to be present except for LeafyCorp, Greenery, and the MongoMenu Button (mentioned above).
image

**Comment by audroue** [comment]
Looks good! Approved ✅

**Review by audroue — APPROVED** [review]

**Pull request merged**
