### PR TITLE
Add Side Navigation Sketch Library

### PR DESCRIPTION
**Pull request by DesignerDave**
Adds the Side Navigation library from the Cloud IA project.

Screen Shot 2020-04-06 at 12 52 26 PM

### CODE REVIEW

**Comment by audroue** [comment]
Heya! Thanks for requesting review.

- I'd pin the Nav item text to the left like on the active state nav item:
image

- If the Nav doesn't resize, I would keep the width of the fields fixed at 160px.

- For some weird reason, when I select an inactive state the layer style is set to active:
image

- Nit: I'd rename "Rectangle" to "Background":
image

- top label should probs allow for multiline support

Looks great otherwise!!

**Comment by DesignerDave** [comment]
Alright, I believe I addressed all your feedback (and removed background color overrides altogether rather than renaming the rectangle hah).

One thing Nelle and I spoke a bunch about was whether to include a 16px padding on the left in each of the symbols (minus the alerts badge). I think I agree with her that the padding helps promote consistency across our products, and thus that takes precedence over the slight annoyance of it not snapping nicely on the left.

I included that as well in my updates!

**Comment by audroue** [comment]
Awesome! 

- Only thing I'd update is the reference and resize each nav item to 176px so that we don't confuse designers when they look at the reference:
image

- I'd also move the alert notification so it doesn't overlap with the text:
image

**Review by audroue — APPROVED** [review]
Looks great!

**Pull request merged**
