### PR TITLE
PD-171: Add Radio Box Library file

### PR DESCRIPTION
**Pull request by DesignerDave**
Adds Radio Boxes as a symbol library.

There are three sets available:
- No margin
- Left margin
- Right margin

Screen Shot 2019-04-25 at 5 09 15 PM

### CODE REVIEW

**Comment by DesignerDave** [comment]
Note: There's an issue with the active boxes when scaling vertically. The boxes will expand vertically disproportionate to the scaling.

@fredtruman Any chance you could look and let me know if you have any ideas?

**Comment by fredtruman** [comment]
@DesignerDave 

1). **re: positioning + scaling** of the active state causing some weird behaviors. Did you try repositioning all the different states so that they fall entirely on the artboard area (so instead of the _deselected_ state starting at (0,0) and _selected_ state starting at (-2,-2) >>> deselected at (2,2) and _selected_ at (0,0))? Positioning the elements outside the artboard might affect how they are scaled  

2). Do you think we should provide an empty radio box to put in any rich content (like some examples from our cluster builder) - or are radio boxes with other / rich content separate elements?

**Comment by fredtruman** [comment]
Nice thanks @DesignerDave ! 

The one unfortunate thing I can see is that the default sizes for lining up a row of selected symbols (margin-right + no-margin + left-margin) is that they end up being sightly slimmer in width than a similar construction of deselected or disabled symbols ... though this might be a necessary tradeoff given the components behavior and probably not an actual use case for the library:
Screenshot 2019-04-30 10 59 20

The only other lingering question I have is whether a left-most radio box intending to be aligned with a column of left-aligned text above will align optically in its selected or deselected state. Examples:

Screenshot 2019-04-30 11 08 43
Screenshot 2019-04-30 11 08 53


If our answer is A I think what we have in this library is right. Otherwise LGTM 👍 :shipit:

**Comment by DesignerDave** [comment]
So the first screenshot is an actual issue, and I'm working on a fix now.

For the second, the answer is indeed A. I think that the interactive example of it best shows the behavior when it's selected. Nothing moves despite the area of the selected option growing (from the addition of the green border). https://mongodb.github.io/leafygreen-ui/?path=/story/radioboxgroup--default

**Comment by DesignerDave** [comment]
Fixed!

**Comment by fredtruman** [comment]
I performed the same check as before, and brilliant! LGTM 🎊

**Review by fredtruman — APPROVED** [review]

**Pull request merged**
