### PR TITLE
PD-283 Symbol: Update Tooltip to New Palette

### PR DESCRIPTION
**Pull request by audroue**
- updated background color
- updated cover

### CODE REVIEW

**Review by DesignerDave — CHANGES_REQUESTED** [review]
Pretty close! Few notes on this:
- The cover image is off by a pixel or two within the artboard – there's a thin white margin on the left side of it.
- The symbols where the arrow is pointing either right or left have a margin on the bottom of the artboards that isn't needed, and would make it harder to align the symbols within designs.

**Review by DesignerDave — CHANGES_REQUESTED** [review]
Looking pretty good! Two notes:
- I think we should have overflowing text clip rather than break out of the tooltips.
- Weren't you going to exclude the arrows from the artboard size?

**Comment by audroue** [comment]
Ahh I had misunderstood what you meant by having the tooltip break out! I now realize you meant, make it break out of the artboard. I think that's smart. I'll update the file.

**Review by DesignerDave — APPROVED** [review]
Great stuff! ✅LGTM

**Pull request merged**
