### PR TITLE
PD-275: Glyphs

### PR DESCRIPTION
**Pull request by DesignerDave**
Boy this actually took some time to do.

This PR adds a set of MDB-custom glyphs as a sketch library file. Each glyph can have it's color changed to any of the colors in our new palette (#8).

Screen Shot 2019-05-24 at 4 03 38 PM

This is the initial set, and we should add new glyphs at our discretion to eventually cover all use-cases for icons we need to deprecate the original library in the original repository.

**HARD DEPENDENCY ON MERGING #8**

### CODE REVIEW

**Review by fredtruman — COMMENTED** [review]
Thanks @DesignerDave !

• Is there a ticket for this? If not, can we create and name the branch after the ticket number?
• How does this file interact with / replace / augment the existing Icon library file?
• Should we provide sizes? Or if we're only providing the one size for the moment, will the organization of symbols provides for that if we want it in the future? Thinking something like:
```
Bell / Small
Bell / Medium
Bell / Large
```

Or:
```
Bell / 16
Bell / 24
Bell / 32
```
(I can't remember the exact sizing scale we discussed, but the idea to name according to numeric scale in pixels)

• What is the `#Reference Grouping` symbol? Do we need it?
• Naming convention? Wondering if we need words like "with" in there (X With Circle)? If we do, begs the question of case in naming conventions... prefer "X with Circle" but also thinking how closely should this match the classnames for easy reference? Just food for thought, this is the font-awesome naming convention: https://makandracards.com/makandra/32149-fontawesome-4+-icon-naming-conventions

• I'm not sure how you feel about this, but I would truthfully prefer a uniform, boring, legible design of our cover pages vs. the (wonderful and unique!!!!) variations in library covers. The uniformity gives me the impression that they fit together, I trust them more as officially created by a team with a process rather than by an individual according to their tastes.

**Comment by DesignerDave** [comment]
1. Whoops – ticket added.
2. This library file is to be the primary file designers go to. The idea here is that we carefully select glyphs to be included over time based on what people find is missing, and eventually replace the legacy file. So check this library first, and if it's not here, the legacy file can help until a glyph is added.
3. The glyphs are all 16x16 right now. We could make fixed sizes for these, though the maintenance burden will become immense pretty quick (not to mention arbitrary sizes can be used in the component as well). If we do supply all the standard sizes, I'd suggest naming according to the components standard size naming.
4. The `#Reference Grouping` symbol is used to construct the name + glyph visual groupings used in #Reference. Otherwise, keeping it up-to-date (or even initially creating it) would be miserable.
5. The glyphs are named according to how they are in code (e.g. `XWithCircle`, `PersonWithLock`), so it's already primed for easy reference. `PersonLock` doesn't work quite as well. They're named that way partly due to limitations in the implementation of the Icon component. These glyphs won't be consumed in code via classNames, so that sort of specification fontawesome does is less important. The prefix is unnecessary, as it's a prop `<Icon glyph="XWithCircle" />`, and additionally we're consistent with the naming now. We always have "with circle" denoting the shape a glyph is in, always have direction last, so we actually have a similar naming convention to them.
6. I'd usually agree, however we're running out of distinct colors quickly. The idea here isn't necessarily to give something design flare, but to make it easy to tell the files apart by their thumbnail. In the below screenshot, we have 4 thumbnails that are variations of blue / teal, and 2 that are green. The text (as large as it is) isn't quite readable, so the only files that are easy to distinguish are the bright pink "Copyable" file, the "Checkbox" file, and the "Palette" file. We might want to consider making the covers simply blown-up examples if there's an issue with standardization.

Screen Shot 2019-05-28 at 2 55 39 PM



Let me know what you think about those points!

**Comment by fredtruman** [comment]
1. 🍬 
2. Sounds good. Should we indicate that the "Icon" file is deprecated or for reference only in the filename?
3. Fair enough, probably can revisit as we find a sustainable way to achieve sizing.
4. 👍 
5. Ok
6. Got it. Maybe we just make a ticket to figure it out at some point. I sort of like the idea of a standard layout potentially adding the #Reference symbol for covers. Non-blocking conversation piece 😁 


- One additional thought: is "Chart" intended to be "Charts" or just a generic "Chart"? Since our side nav within Atlas has changed, those icons (Stitch and Charts) are no longer in play any where. Should we scrap them if they are intended to represent the products?

**Comment by DesignerDave** [comment]
2. We aren't including the original icon file in this repo. By its nature, the entire other repository is becoming deprecated.
3. We could probably create a symbol for each size that we can reuse across icons – might make it easier. I'm just trying to keep in mind the day this library has upwards of 50 glyphs, and keeping those up-to-date could become burdensome as-is without the size variations.
6. Yep – It can probably be addressed in a better way, but the standard we've been using isn't scaleable.

That's a great question... I had it as generic "chart" but I'm open to scrapping it if you feel strongly we should.

**Comment by fredtruman** [comment]
2. Ah - that's right. 👍 
3. Ok, so are you fine leaving as is or would you prefer to scope these that we have current to a size to be able to fill in other sizes? Defer to your judgement here

Maybe we just keep "Chart" as generic "Chart" and rename the "Stitch" icon to something else more generic ("Dashboard"?) or scrap it for now if there's no other clear use for it. 

Otherwise LGTM

**Comment by DesignerDave** [comment]
3. I might play a bit with scaleable approaches to sizes for these before merging. I don't want to rule it out completely...

I might remove the app-specific glyphs altogether. They seem very niche, and nearly unused now that the nav has changed... That said, I should also remove them from the `leafygreen-ui/icon` package if that ends up being the case.

**Comment by DesignerDave** [comment]
Screen Shot 2019-06-03 at 4 20 17 PM
Screen Shot 2019-06-03 at 4 31 02 PM

Added / updated the above glyphs.

On the sizing, I haven't found a good way to apply sizing as an override or a layer style, and maintaining 3 versions of each icon seems very difficult to maintain. The best I could think of is providing symbols for each size that you can use by overriding the glyph for each.

The library would look like:
```
Sizes >
    Default
    Large
    Extra Large

Glyphs >
    ...All Glyphs
```

Let me know if you'd prefer that implementation.

**Comment by fredtruman** [comment]
@DesignerDave Those glyphs look great 👍 

Oh interesting re: the library layout for sizes. I think that sounds like a decent plan, actually. Would the "All Glyphs" symbols be sized @ the default sizing, and then each size option (aside from default) just scales the glyph? That would actually only be a minimal addition to the file we were creating anyways, right?

**Comment by fredtruman** [comment]
Nice @DesignerDave - really like this solution to sizing.

The menu order, where `Sizes` are co-mingled with the glyphs, leaves the user potentially a little confused in figuring out how to use the library. Wonder if you considered any other organization options? Like:

```
#Reference 
#Reference Grouping
Default
Large
X-Large
Glyphs >
```

or maybe

```
#Reference 
#Reference Grouping
Sizes >
Glyphs >
```

?

Any thought on size names like:
```
Small (Default)
Medium
Large
```
?

**Comment by DesignerDave** [comment]
I like:
```
#Reference 
#Reference Grouping
Sizes >
Glyphs >
```

I'll implement that.

As for the size names, I named them according to the component's available props, and I don't think that should be changed.

**Comment by DesignerDave** [comment]
RFAL @fredtruman! Hopefully it's good to go now.

**Comment by fredtruman** [comment]
LGTM :shipit:  @DesignerDave

**Pull request merged**
