### PR TITLE
PD-227: Apply new palette to checkbox

### PR DESCRIPTION
**Pull request by DesignerDave**
https://jira.mongodb.org/browse/PD-277

This updates the checkbox library to the new palette!

### Before
Screen Shot 2019-07-24 at 1 42 32 PM

### After
Screen Shot 2019-07-24 at 1 46 43 PM

Also, utilized symbols more heavily in the creation of these – pay special attention to the menu organization for them! Found a pattern I rather like for "internal symbols" and want your thoughts on it.

### CODE REVIEW

**Review by fredtruman — COMMENTED** [review]
Aye overall LGTM!
• For text styles, yeah I think its fine as you have it. This was the same thing we used for the Button library as well. If people want to use them, they can ... but they can mostly be ignored by consumers and makes updating a library so much easier.
• I like the idea of having a menu bucket of internally used symbols that aren't really for consumption, my only questions are 1). if leaving it blank is the way to go vs. naming the bucket like "internal" or something else would be better, and 2). not sure #Reference makes sense in this bucket ... I kind of like having it handy at the root menu, but may just be me.

Feel free to shipit, but I think the most important thing is consistency with other library files for knowing when a symbol is something for me to use in my design vs. something to be used by the library creators/maintainers. I might suggest keeping #Reference at the root which would keep this consistent with others for now without having to update them

**Comment by DesignerDave** [comment]
@fredtruman I think the reason to remove #Reference from the root would be to reduce clutter. I think there's something to be said about a clean menu with only the symbols you're actually gonna use.

I think the same argument could be made for keeping it blank instead of naming it something like "internal". I definitely think blank bucket sections is the way to go. Eventually they are likely to add the ability to hide symbols from libraries, since they've already done that for the inspector.

If you feel strongly that #Reference symbols will actually be used by consumers, then we can keep it.

**Comment by fredtruman** [comment]
Nope I don't feel strongly about where #Reference goes @DesignerDave , though I think modifying that location for this library will potentially create labor to bring existing libraries up to parity. I'm ok with that if you are!

**Comment by DesignerDave** [comment]
I don't think it's high priority, but as we go through updating these files, let's move #Reference for the sake of consistency.

**Review by fredtruman — APPROVED** [review]

**Pull request merged**
