### PR TITLE
Added minus symbol to symbols

### PR DESCRIPTION
**Pull request by NicelyStrange**
Also renamed some layers, added the symbol to the reference page

### CODE REVIEW

**Comment by audroue** [comment]
Hi Jimmy! Great job on your first contribution. 🎉

Looks like the minus symbol you added has a thicker line-weight then the plus symbol in the library. Also, the browser uses aliasing on the edge of the graphic if the graphic isn't on the pixel grid, so whenever possible we try to align graphics to the pixel grid (reference: https://www.grc.com/ctwhat.htm)

image

**Comment by NicelyStrange** [comment]
Thanks Rob!

Yes, that pixel offset was intentional. In my opinion 2px was slightly too thin, and 3 or 4px would be too thick. If you zoom out to 100% and review the minus icon in proximity to the plus icon, the plus icon's surface area overpowers the surface area of the minus icon. I would like to balance them both as they will sit next to each other in use. And as the plus is a heavy style I thought the minus should be too.

Screen Shot 2019-12-13 at 9 33 17 am

I think breaking the grid in this case would be fine. If I look at the other icons in the set we have taken some discretion to do the same in certain cases.

Screen Shot 2019-12-13 at 9 33 34 am
Screen Shot 2019-12-13 at 9 33 49 am

I know this shape is the most basic shape in our set and easy to snap on the grid. I would challenge the rule and say craft icons for use first and foremost.

**Comment by audroue** [comment]
Hi Jimmy. Thanks for clarifying the reasoning for enlarging the minus symbol. 

I'm still not convinced we need to alter the size of the minus symbol and make it stretch outside the pixel grid. I did some tests below and you can see that on a non-retina screen the minus icon that extends beyond the pixel grid is quite blurry whereas one that isn't remains sharp while still balanced with the plus symbol. 

The aliasing is most pronounced on a non-retina screen, as shown below: 
non-retina screenshot

Here's what it looks like on retina (blur is less present but still there):
Screen Shot 2019-12-13 at 11 07 10 AM

Based on the image above you shared, it looks like you're trying to use this icon at 20px? It could be that at that larger size it warrants the optical sizing changes (in relation to the + icon) that you're proposing, but at the current 16px I think it should be set on the pixel grid so as not to incur the aliasing/blur affect illustrated above.

**Comment by NicelyStrange** [comment]
Thanks Rob.
When you place it like that on a non-retina screen I agree it looks too blurry in comparison to the other icons.
We don't want that.
I am happy to set it back to the pixel grid.
Without the ability to blur an edge, even one side, the challenge we have is the 2px thickness feels thin in comparison to the plus symbol.

Screen Shot 2019-12-14 at 7 40 12 pm
Screen Shot 2019-12-14 at 7 40 24 pm

Here I've shown a 2px and 3px variant.
What do you prefer?
Is my concern over even thickness warranted?

I understand the importance of sweating the details on the icon library/Sketch library to ensure a pixel perfect set as foundation.
In the real world application of the icon file, for this use case in Charts, we want to scale the starting size (16x16px) to a 20x20px size for use in the "normal" button size.
This raises another question - what sizes should the icon files be scaled at, to preserve the sharpness you desire?
In my experience once an icon library is published its very hard to govern its size and appearance in the real world.
Anti-aliasing is handled differently by OS.
Sizes in the DOM should be predictable, but the presentation of the shapes can vary between browsers.
And sometimes sizes become fractional/decimal depending on the set up of the stylesheet.
Some things for you and the team to think about if governing this is priority.
Thank you

**Comment by audroue** [comment]
Hi Jimmy,

I think the 2px version works great. Ideally, we'd have different icons for different sizes to account for these sorts of optical issues. Re: icons in general, I think Kalie Patterson and her team is going to be working on these from now on.

**Comment by NicelyStrange** [comment]
Hi Rob, I've updated the file and pushed a new comitt. Please review it and approve if all good. Thanks

**Review by audroue — COMMENTED** [review]
Looks great! ✅

**Comment by fredtruman** [comment]
Hi @audroue - what's out next step here? Do we need additional approvals or is this good to merge?

**Comment by audroue** [comment]
Hi @fredtruman, looks like the next step would be for someone else to approve the PR on top of my approval.

**Review by audroue — COMMENTED** [review]
Looks great! ✅

**Review by DesignerDave — APPROVED** [review]

**Comment by DesignerDave** [comment]
@NicelyStrange You should be good to merge this whenever you're ready to! Once it's merged in, we'll make the update to the file on Google Drive.

**Pull request merged**
