### PR TITLE
PD-131: Core Palette Updates, Adjustments, Consolidations

### PR DESCRIPTION
**Pull request by fredtruman**
**Changes:** @DesignerDave 
- New colors (_adjustments and consolidations_)

Screenshot 2019-05-01 16 30 38

- Added layer styles for each

Screenshot 2019-05-01 16 31 06

- Added Core document swatches for each to color picker

Screenshot 2019-05-01 16 31 57

**A couple implications of this color change downstream:**
- Colors at `00` values have been chosen to meet AA contrast standards when used in conjunction with text at `N90` (white), or their corresponding `70` values (for example, `B00` text used on top of B70 text will meet or exceed those standards)
- Symbol libraries inheriting the Core file swatches will need to be updated
- If we moved away from teal/aqua as accent color in favor of this family of blues:

Screenshot 2019-05-01 16 49 40

Screenshot 2019-05-01 15 34 27

### CODE REVIEW

**Comment by fredtruman** [comment]
@DesignerDave - if we're more or less aligned on this direction, since this repo isn't widely used _yet_ my thinking is to get this swiftly onto master in order to adopt the palette on `Badge` and a new `Banner` library, as well as push the color changes to the other existing libraries in order to better understand the implications in practice.

**Comment by DesignerDave** [comment]
Two main questions with this PR that I think are important:
1. Should we be providing the `30` and `60` range auxiliary colors? I could see limiting them to `00`, `10`, and `70` ranges. I like the naming.
2. While I like that blue, I feel that from a branding perspective, it shouldn't stand out as much as the green. The current blue avoids that. Thoughts?

**Comment by DesignerDave** [comment]
On the brand issue, I will say I LOVE this blue, just that I'm concerned about it dominating the page.

**Comment by fredtruman** [comment]
Hey thanks @DesignerDave 
1). I was considering just leaving with 00, 10, and 70, but then I thinking through some of the situations where we'd need to adapt existing blue usage I figured it couldn't hurt to have some aux range swatches available in the 30/60 range (chart type icons for example looked super weird just using 00/01 + 70) 
2). Yeah totally fair point. By _current blue_ do you mean current blue used for links or the aqua/teal? I think I agree that the blue shouldn't necessarily dominate, but also think the aqua/teal is equally over-powering without any intentionality behind it. The Compass example is a bit extreme in that it's data-viz heavy (which we should devise standards for in addition to this), but most views would really have the blue only as links most likely. I do think it might be worth exploring a value not at `10` for standard use (like for links) since it is so bright and potentially over-powering as you mention. For reference:

Current Atlas screenshot (looking at link blue):
Screenshot 2019-05-01 20 43 38


Atlas screenshot with `B10` as links:
Screenshot 2019-05-01 20 43 50


... and Atlas screenshot with `B00` as links:
Screenshot 2019-05-01 20 44 01

**Comment by DesignerDave** [comment]
1). Fair enough. Could we expand upon the names then to steer people towards certain colors? This would hopefully steer people towards those colors without making them exclusive. I'm thinking like font-weights on the web - You can set the weight as `100, 400, 700`, but you know them by `light, regular, bold`. Example:
  ```
    B00 [Dark]
    B10 [Primary]
    B70 [Light]
  ```

2). I disagree - the current blue feels less weighty, and draws less attention on the page. That may be in part due to it being warmer than the original, and thus further from the brand green. I think that we should standardize `10` as our standard blue, and should tone this down a little bit - either through color temperature, saturation, or both. Having a small teal tint to the color might not be the worst. Perhaps somewhere in the middle of where we were and this?

As a side-note: Your link example probably should use `10` rather than `00`.

**Comment by fredtruman** [comment]
Thanks @DesignerDave !

1). Nice idea, I've annotated those values with a naming convention:
Screenshot 2019-05-02 15 33 57

2). While I don't disagree with this point, I am not informed properly to make a conclusion one way or the other on the value of blue. One thing I do feel pretty good about however, is consolidating our blues to a finite set in this manner, and then inheriting from this finite set for our other component symbol libraries. If not the actual hex value of Blue, do you think the framework is appropriate enough that we can consult further with stakeholders (setting some up now) and swap in an agreed upon value in the near future? Would you prefer some other existing blue value as a more appropriate placeholder? My thinking is to drive the framework forward to unblock soon-to-be-worked on elements!

**Review by DesignerDave — APPROVED** [review]
Alright, consider yourself unblocked! I do want to be sure we revisit it though, if only to confirm it's use. Looks like we may be tomorrow!

**Pull request merged**
