### PR TITLE
PD-253: Info Sprinkle

### PR DESCRIPTION
**Pull request by fredtruman**
Screenshot 2019-05-02 16 06 28

Screenshot 2019-05-02 16 08 37

@DesignerDave

### CODE REVIEW

**Comment by DesignerDave** [comment]
Hmm... This style shadow isn't something we've done before to my knowledge. Not sure this component justifies adding it.

Have we used this shadow style at all anywhere?

**Comment by fredtruman** [comment]
Sorry - do you just mean the hover state @DesignerDave 🤔 I just through that in there, but not attached to it in any way.

**Comment by DesignerDave** [comment]
Unless I'm missing something, it looks like the static one has the same shadow style as well.

**Comment by fredtruman** [comment]
Oh I think that's just the way it appears in the Sketch menu 🤔 There shouldn't be any shadows on the elements themselves:

Screenshot 2019-05-03 12 22 35

**Comment by DesignerDave** [comment]
Ahh, that's what I was confused about. Any thoughts towards the info tooltip appearance? We were talking about having it appear on clicking the sprinkle, and have a bit of a different appearance given the behavioral difference.

**Comment by fredtruman** [comment]
I haven't thought too much more about that. Two approaches:
- Continue the thoughts, consider syncing with Docs design team
- Merge the sprinkle by itself for now, revisit tooltip specifics and include in this library if needed

? Thoughts @DesignerDave

**Comment by DesignerDave** [comment]
Don't agree with that approach – the info tooltip is an essential piece of the info sprinkle that will be a part of every single one in the wild, and it wouldn't make sense to ship the symbol without that piece of the puzzle. This component shouldn't be blocking other work at the moment, so I think it's alright to spend some time talking about it and not rush it out.

**Comment by DesignerDave** [comment]
And I'm not sure how much the Docs team needs to be involved. This is a component that fills an existing role in the product, and just needs to accommodate those use-cases.

**Comment by DesignerDave** [comment]
Closing this PR to keep the list clean. Will still be available for reference in the closed PRs list.

**Pull request closed without merging**
