### PR TITLE
PD-524 Design Tables

### PR DESCRIPTION
**Pull request by audroue**
Added Tables library file

### CODE REVIEW

**Comment by DesignerDave** [comment]
Hey Rob! Been playing with this library – this is gonna be amazing for designers to have!

Here's some points I came across where the components might be able to be improved:
- We should probably disable all overrides that could go against our guidelines. The ones that stick out to me are the color overrides for glyphs in column headers, and I also feel like some of the glyphs themselves could probably have overrides disabled (though you may have had a reason to leave them).
- Does the “Add Column” symbol need to exist, or can it be built with other symbols in the library? It seems weird to have a symbol representing two cells in a column when the rest are one. Additionally, “Add Row” doesn’t include an additional column. 
- `-1` and `-2` representing nesting levels was confusing for me. Perhaps renaming them to something more explicit like “Nested / One Level” and “Nested / Two Levels” or something similar would be better.
- Table headers should probably be constrained to a single line, and thus the symbol shouldn’t be able to be resized vertically. Though, if it should be able to be resized vertically, there needs to be some attention paid to the pinning of the icons and text.
- The "Row Selector" symbol (the vertical blue line) should have its width locked to promote consistency. Also, should this be named something other than “Row Selector”? Sounds like an input. Maybe “Row Selected State” would be more clear. Additionally, it seems to share a name with the checkboxes under “Other Features” in editable tables.
- What was the thought behind including the unselected row indicator?
- More meta note, should we rely on our existing symbols for things like “Add Column” or the checkboxes? I feel like it’s unnecessary to include them here, and it wasn’t intuitive to me that you’d find those in this library.

As a more meta note, since this is one of our most complex libraries to date, it may be worth doing some lightweight user testing, and see how easily designers are able to find and use the library. That could be a great addition to our process if it goes well.

**Comment by audroue** [comment]
Thanks for the feedback! I've added some comments below:

- We should probably disable all overrides that could go against our guidelines. The ones that stick out to me are the color overrides for glyphs in column headers, and I also feel like some of the glyphs themselves could probably have overrides disabled (though you may have had a reason to leave them).
**Yeah, def some of the glyphs need the color override turned off. I'll do some more work on these. For some odd reason even when I turned it off it still showed up on some, but I'll revisit that.**

- Does the “Add Column” symbol need to exist, or can it be built with other symbols in the library? It seems weird to have a symbol representing two cells in a column when the rest are one. Additionally, “Add Row” doesn’t include an additional column.
**I think if we don't include these symbols people are going to resort to their own DIY execution of these actions. If we're ok with that we can remove them. Another option is I can try to make the add column look more like the add row symbol — so they both take up only 1 cell space. I think that might be a good solution.**

- 1 and -2 representing nesting levels was confusing for me. Perhaps renaming them to something more explicit like “Nested / One Level” and “Nested / Two Levels” or something similar would be better.
**That makes more sense. I'll update this to your recommendation.** 

- Table headers should probably be constrained to a single line, and thus the symbol shouldn’t be able to be resized vertically. Though, if it should be able to be resized vertically, there needs to be some attention paid to the pinning of the icons and text.
**Yeah, the icons are all pinned to the bottom of table headers. I tried to pin the text too (when it extends to two lines) and was not able to find a solution (since text in Sketch seems to overflow downwards and never upwards). I think allowing 2 line headers would be nice though considering some of our current tables have/require it.**

- The "Row Selector" symbol (the vertical blue line) should have its width locked to promote consistency. Also, should this be named something other than “Row Selector”? Sounds like an input. Maybe “Row Selected State” would be more clear. Additionally, it seems to share a name with the checkboxes under “Other Features” in editable tables.
**I like that idea. I'll rename it. I thought its width was locked. Guess it was not. Good catch. I'll fix that.**

- What was the thought behind including the unselected row indicator?
**I think I need to add an empty/unselected state for the symbol to appear in the panel. I'll see if I can simplify it and omit it.** 

- More meta note, should we rely on our existing symbols for things like “Add Column” or the checkboxes? I feel like it’s unnecessary to include them here, and it wasn’t intuitive to me that you’d find those in this library.
**Sure thing. I can remove them from the symbol library. I think retaining the guidelines for their usage might still be valuable. Thoughts?**

- As a more meta note, since this is one of our most complex libraries to date, it may be worth doing some lightweight user testing, and see how easily designers are able to find and use the library. That could be a great addition to our process if it goes well.
**Sure thing. Currently I already gave Dipesh, who's working on a table feature the file. Hopefully he can give us some feedback. Otherwise, how would you recommend I gather feedback? One idea is to hand this file to the DS panel to play around with and see if they have thoughts or concerns.**

**Comment by DesignerDave** [comment]
> Yeah, def some of the glyphs need the color override turned off. I'll do some more work on these. For some odd reason even when I turned it off it still showed up on some, but I'll revisit that.

Sweet 👍

> I think if we don't include these symbols people are going to resort to their own DIY execution of these actions. If we're ok with that we can remove them. Another option is I can try to make the add column look more like the add row symbol — so they both take up only 1 cell space. I think that might be a good solution.

I'm of the mindset that we should trust designers a little, and that people who would design their own implementation probably aren't looking through the symbol library for the functionality in the first place. We have guidelines, so we have a place to point if someone does implement add column / row functionality in a way that's against our recommendations.

> That makes more sense. I'll update this to your recommendation.

👍 

> Yeah, the icons are all pinned to the bottom of table headers. I tried to pin the text too (when it extends to two lines) and was not able to find a solution (since text in Sketch seems to overflow downwards and never upwards). I think allowing 2 line headers would be nice though considering some of our current tables have/require it.

I don't feel super strongly about the multiline aspect, as long as the symbol supports it well. 👍 

> I like that idea. I'll rename it. I thought its width was locked. Guess it was not. Good catch. I'll fix that.

👍 

> I think I need to add an empty/unselected state for the symbol to appear in the panel. I'll see if I can simplify it and omit it.

👍 

> Sure thing. I can remove them from the symbol library. I think retaining the guidelines for their usage might still be valuable. Thoughts?

100% think we should keep the guidelines! It's just nice to be able to rely on our existing symbols to design, and have less symbols in each of our library as a bonus.

> Sure thing. Currently I already gave Dipesh, who's working on a table feature the file. Hopefully he can give us some feedback. Otherwise, how would you recommend I gather feedback? One idea is to hand this file to the DS panel to play around with and see if they have thoughts or concerns.

You might consider grabbing a couple designers and doing effectively an actual user test with them – have them use the library in front of you, prompt them to design things, and see how effectively they can find parts of the library, align items, etc.

**Comment by DesignerDave** [comment]
Hey Rob! Couple more things I found:
- `_Column Label` -> `_Column Header` – The terminology for this seems fairly standard, and is even reinforced by the HTML name: `<thead>`.
- `_Editable Table` -> `_Editable Table Cells`, `_Non-Editable Table` -> `_Non-Editable Table Cells` Given most of the content in both categories is table cells, I think this would improve the ability to find symbols. You could move the row selection indicator outside of this category in that case, if you think that'd be best.
- Constraints on bottom and top overflow shadows don’t seem to be working right when expanding them vertically – looks like a size constraint isn’t applied.
- The only way to align the bottom border of a table header with the borders on top of a table cell is by manually setting the `y` value in the sidebar to a `.5` amount. When aligned without subpixels, it looks like this:
Screen Shot 2020-04-14 at 3 12 01 PM
- The bottom left and right corners of table headers have a little "chip" in them (likely because of a border that's misaligned):
Screen Shot 2020-04-14 at 3 15 29 PM

**Comment by audroue** [comment]
Good 👁— made the changes!

**Review by DesignerDave — APPROVED** [review]
LGTM!

**Pull request merged**
