### PR TITLE
PD-363: Create sketch library for loading indicator component 

### PR DESCRIPTION
**Pull request by sampoonachot**
Drafted rough concepts for 3 types of loading indicators, which include: 
* progress bar
* spinner
* skeleton loader

Loading Indicator

### CODE REVIEW

**Comment by DesignerDave** [comment]
I'm digging the progress bar! Some things to consider with it:
- Do we want to offer a compact version of the progress bar? Maybe that variant could be a circular progress bar with the percentage inside? Just some thoughts.
- Where would we display additional information on what's happening? Do we even want to display that sort of information? One case my mind goes to for this is deploying a cluster – perhaps the user may want to see information on what node is being spun up, or whether the mongod processes are being started. It's good validation that _something_ is happening and that it's not stuck.
- I'm wondering about the percentage aligned to the right of the progress bar. It looks good here but in practice it may be harder to create strong vertical rhythm when that rhythm is disrupted on the right side. Any consideration to putting it above or below the bar? Right-aligning it underneath, for example, might look pretty good, and also give a logical space to the left for additional information on progress, if desired.

For the spinner, I think we should consider moving away from a simple spinning icon, and move towards an animation that's a bit more lively. Here's an example I made at mLab and tweaked a bit with the MDB base green: https://drive.google.com/file/d/1lnSjbdOQ13BlixulqPGIsk-g59pnFCpE/view?usp=sharing

As far as the skeleton state, that's probably going to be integrated directly with each component. I like where you're going with it though. Any thoughts about whether we should have any motion in the state? Facebook has a shifting gradient for example. One thing that might be cool is some sort of animated outline going around each block. The purpose of the motion would be to indicate something's happening, rather than everything feeling static.

**Comment by sampoonachot** [comment]
Screen Shot 2019-08-02 at 10 10 41 AM

@DesignerDave what you mentioned makes sense! For now, what I've created are just proposals which I hope your team could adopt and tweak with more lively animations and colors. I added a radial progress bar, but kept these indicators all in the same file to make it easier for review. Will separate later. 

* Re: the progress bar, how do you feel about the alignment and the size?
* Re: the spinner, for now since most teams are using either `spinner`, `spinner-third`, or `mms-spinner`... I decided to use `spinner` (since it's free and accessible to all products), but once the spinner icon is created by your team we can replace it. There are 2 libraries that would need to be modified 1) Buttons 2) Spinner
* Re: skeletons, happy to take your suggestions! I don't think I'm the person to be animating these components but I've mocked up a quick example using Anima, which you can preview in the sketch file

**Comment by DesignerDave** [comment]
@sampoonachot

- Ahh, I love the updated progress bars! They feel much better IMO. I wonder if the "Processing..." text and the percentage should be a light gray though. Thoughts on that? Maybe that sort of thing is outside of the purview of a proposal...
- I was thinking with the radial progress bars, perhaps we should remove the percentage so that they can be more compact? My thought behind this is that we could have inline progress bar-like indicators for things such as tabular data, or more compact spaces. I don't know that at its current size, it would offer a benefit over using the horizontal progress bar. Love to hear your thoughts on this in relation to the guidelines.
- On spinners, that makes sense. I think we're gonna want to replace that with something more dynamic soon.
- The animation seems pretty nice so far. Definitely conveys the idea at the very least, but also doesn't feel far off.

**Comment by sampoonachot** [comment]
> I was thinking with the radial progress bars, perhaps we should remove the percentage so that they can be more compact? My thought behind this is that we could have inline progress bar-like indicators for things such as tabular data, or more compact spaces. I don't know that at its current size, it would offer a benefit over using the horizontal progress bar. Love to hear your thoughts on this in relation to the guidelines.

I agree it would make sense to have a radio progress bar that's more compact, I just haven't seen a use case for it yet. However, that doesn't mean we can't provide sizes.. 

Screen Shot 2019-08-08 at 7 31 49 AM

**Comment by DesignerDave** [comment]
So the use-case for this sort of radial progress bar is more inline usages such as Google's in Drive:

Screen Shot 2019-08-07 at 3 09 40 PM

We don't necessarily have this implemented anywhere in the UI, but I'm sure it will come in use. This sort of case we'd otherwise need to refer people to a spinner for when we could offer the user more information, and the feeling that things are actually happening.

**Comment by sampoonachot** [comment]
> This sort of case we'd otherwise need to refer people to a spinner for when we could offer the user more information, and the feeling that things are actually happening.

Ah! I totally misread the direction and thought of it as a chart for some reason. Thanks for clarifying. 
Screen Shot 2019-08-08 at 8 30 47 AM

**Comment by sampoonachot** [comment]
@DesignerDave @fredtruman checking if there are any open questions or concerns before I split the sketch library into 3 files: Progress Bars, Spinners, Skeleton Loaders

**Comment by DesignerDave** [comment]
@sampoonachot I'm excited. Let's go for it.

**Comment by sampoonachot** [comment]
Updated `Buttons` with the new spinner:

Screen Shot 2019-08-13 at 2 43 55 PM

Separated `Loading Indicators` into `Progress Bars` `Spinners` and `Skeleton Loaders`:

Screen Shot 2019-08-13 at 2 44 51 PM
Screen Shot 2019-08-13 at 2 45 01 PM
Screen Shot 2019-08-13 at 2 45 11 PM

**Comment by DesignerDave** [comment]
Hey, sorry it took so long to get around to reviewing this –

### Spinner
I'm hesitant to include text as a part of this symbol, at least until we have LeafyGreen text styles that we can have available as overrides. I don't think that color / size text will support many of the use-cases needed for spinners.

I think for now, it would probably be fine to only have a standalone spinner symbol for now until the text styles are available. Additionally, we could then use that spinner symbol as a part of the button component!

### Progress bar
Love the "length" override! Wondering what your thought was in including two symbols here? It may be fine to simply have one symbol with the two text statuses (status, completion). If a design only calls for one or neither of those things, the text overrides should be able to be set as blank.

If that feels like a workaround, I hear ya. If you feel we should keep the two symbols, could you name them something more descriptive? Right now they have the same name, so finding the right one is trial and error.

Additionally, we were talking about adding a radial progress bar. Did you mean to include that? It appears to be in the library file, just not as a symbol.

### Button
Only a couple things with the button updates. First, it would be great to use the spinner symbol straight from the spinner library. That'll make it easier to update in the future, if needed, and ensures consistency.

Second, The spacing between the text and spinner in the small and extra-small button variants feels too narrow. Additionally, the spinner feels rather large in the context of the extra-small button. We might want to consider having a `default` (16px) variant and `small` (14px) variant to support this sort of case. I don't think the extra-small button with loading indicator pattern will be frequently used, but it's worth supporting that if needed.

### Skeleton
I think this was intentional, but there aren't any symbols in the library file. I think this file should actually be alright to remove entirely, and we can make tickets to add skeleton states to existing components and library files, since I don't see it as its own component, but rather a state of existing components.

**Comment by DesignerDave** [comment]
Closing this PR to keep the list clean. Will still be available for reference in the closed PRs list.

**Pull request closed without merging**
