### PR TITLE
PD-599 Cleaned up MongoMenu symbol for team usage

### PR DESCRIPTION
**Pull request by audroue**
- Removed hover, focus, pressed, and disabled states
- Consolidated symbols into 7 main symbols for designers to use
- Cut down on how much of the menu can be edited so as to limit confusion and simplify usage
- Fixed minor spacing and visual bugs

### CODE REVIEW

**Comment by DesignerDave** [comment]
Hmm... there seems to be some strange things happening in the symbol that breaks the visual appearance of it.

https://drive.google.com/file/d/1o2-J1MpzPH1DckYVPmc9ytmFOhW4QK2O/view?usp=sharing

**Comment by audroue** [comment]
Wow weird. Thanks for the feedback. I'll look into that.

**Comment by audroue** [comment]
Very weird. I'm not able to reproduce it just yet, but I'll keep on looking 👀

**Comment by audroue** [comment]
Hey Dave! Tested this with Allison and she didn't have any issues on her end. Maybe it's something with your Sketch app or computer? 🤷🏻‍♂️

**Comment by DesignerDave** [comment]
I think I found the issue – I believe it's related to the Anima plugin I had installed. I disabled it and the library works as intended!

**Review by DesignerDave — APPROVED** [review]

**Pull request merged**
