### PR TITLE
PD-276: Update Button Library with New Palette

### PR DESCRIPTION
**Pull request by fredtruman**
WIP

Preview colors: https://mongodb.invisionapp.com/share/WDSE8VJU8K5#/367479751_static

### CODE REVIEW

**Comment by fredtruman** [comment]
Screenshot 2019-06-10 12 56 30

**Comment by fredtruman** [comment]
RFAL @DesignerDave

**Comment by DesignerDave** [comment]
As we discussed, specifically for "Danger" buttons, I'd look at a gradient similar to `#E45B26 <=> #B63016`.

Otherwise these LGTM!

**Comment by fredtruman** [comment]
@DesignerDave I've updated the danger gradient to #E45B26 <-> #B63016 for the static state and adjusted for hover and pressed accordingly. Ready to merge otherwise if LGTY

Screenshot 2019-07-18 14 28 05

**Review by DesignerDave — APPROVED** [review]
Looks good! New danger buttons match up well with our palette.

**Pull request merged**
