### PR TITLE
PD-221: Add checkmark glyphs to glyph library

### PR DESCRIPTION
**Pull request by DesignerDave**
Adds the following glyphs to the library:

Screen Shot 2019-06-11 at 6 03 08 PM

### CODE REVIEW

**Comment by DesignerDave** [comment]
I also made the other circle glyphs a bit smaller!

**Review by fredtruman — APPROVED** [review]
Nice, those glyphs LGTM 👍

**Comment by fredtruman** [comment]
Couple small unrelated notes:
- Is there a ticket for this? Can we continue to name the branch and PR with that context?
- Just did a quick test with these glyphs for Badges. I think if we had a warning and info icon that matched the size and feel of "x" and "checkmark" (no circle) then we'd have something for those specific badge instances. We can continue to discuss that independent of this PR!

Screenshot 2019-06-12 10 52 35

**Comment by DesignerDave** [comment]
Ticket existed, my bad on not adding it here.

https://jira.mongodb.org/browse/PD-221

**Pull request merged**
