### PR TITLE
PD-278 Update Copyable Color to New Palette

### PR DESCRIPTION
**Pull request by audroue**
- updated background color
- updated font color
- added border radius
- added border

### CODE REVIEW

**Comment by DesignerDave** [comment]
Sweet! There's a few things I'm noticing that are a result of the library being a direct port of the old one that we should probably take a look at and improve.

- The buttons don't use the buttons from our library. This wouldn't really be noticeable with the primary green buttons, but is very obvious when it comes to the default ones.
- We should probably make the button variants a symbol override, and default to the "Default" button variant. I don't imagine there are may cases where you will want a primarily CTA button variant for a copy button – connection string aside.
- Right now, there are a ton of size variants. I think we should do a couple things here to simplify the library, but hoping @fredtruman can weigh in on this one:
  - We should limit the font size for monospace font in the copyable component to `13px` to be consistent with the existing code component, and to limit divergent applications of font sizes – especially when the size differences between sizes are 1-2px.
  - We should offer 1 or two sizes, and the only difference between them should be the padding. Having 4 sizes for the component seems unnecessary for the time being, and I have massive doubts we use or would want to use the "Large" or "X-Small" size variants.

**Comment by fredtruman** [comment]
Hey there - what you're saying makes sense Dave. We can probably kill the `large` and `x-small` variants and consolidate the `small` and `normal` sizes it makes sense. So the library might look like:
- Code Block
- Line of Code

then maybe the color variants:
- Light
- Dark

then the button variants within that?

**Comment by DesignerDave** [comment]
Ahh yes – would be good to offer color variants here like we have in the react component. Good catch!

**Review by DesignerDave — DISMISSED** [review]
This looks really great @audroue!

The only thing I can think of the improve it at the moment is to maybe call them something like `Single Line` and `Block` rather than `Line of Code` and `Code Block`. The naming seems a bit prescriptive, especially with the single-line variant.

Approving this – I'm not entirely convinced it needs a rename, so feel free to merge if you don't think it needs the change.

**Review by DesignerDave — APPROVED** [review]

**Pull request merged**
