### PR TITLE
PD-744 Add Example Call-Out to Call-Out library

### PR DESCRIPTION
**Pull request by audroue**
- Added Example Call-out
- Corrected some overrides available

### CODE REVIEW

**Comment by DesignerDave** [comment]
Could you add the glyph to our library as well?

**Comment by audroue** [comment]
Thanks for the review! Agreed we should include the glyph in the library. Diancheng recommend one of these, specifically we were leaning towards the middle one. Got a preference? If not, I'll add the paperclip and note glyph (middle one) to our library and add in the Call-Out. 

image

**Comment by DesignerDave** [comment]
Oh interesting. I was already getting attached to the beaker glyph you used! haha

I think it relates more closely to the content of an example call-out than paper or notes.

Screen Shot 2020-07-29 at 2 18 57 PM

**Comment by audroue** [comment]
I like the beaker too! Let's stick with that for now.

**Review by DesignerDave — DISMISSED** [review]
LGTM!

**Review by DesignerDave — APPROVED** [review]

**Pull request merged**
