### PR TITLE
Pd 432 create text input sketch symbols

### PR DESCRIPTION
**Pull request by audroue**

### CODE REVIEW

**Comment by fredtruman** [comment]
Nice! I noticed resizing the error symbols moves the message down:

Screenshot 2019-12-17 14 17 21
Screenshot 2019-12-17 14 17 26
Screenshot 2019-12-17 14 19 35
Screenshot 2019-12-17 14 19 41

**Comment by audroue** [comment]
Thanks for the feedback! Yup that's something I'm aware of. I might be able to fix that with:  https://www.sketch.com/features/smart-layout

**Comment by fredtruman** [comment]
You should be able to just pin the error message to a specific Y coord so that it _resizes vertically_ as the entire symbol resizes vertically, vs. _floating in the middle and moving down_ as the symbol resizes vertically.

**Comment by audroue** [comment]
Looking into it!

**Comment by audroue** [comment]
Fixed error message resizing issue.

**Comment by fredtruman** [comment]
Nice! Confirmed, looks good:
Screenshot 2019-12-19 10 46 17

**Review by DesignerDave — APPROVED** [review]
Looks good! Excited for these.

**Pull request merged**
