### PR TITLE
Add brand-aligned palette library

### PR DESCRIPTION
**Pull request by DesignerDave**
Adds the following palette to our set of Sketch libraries:

Screen Shot 2019-05-20 at 4 50 28 PM

### CODE REVIEW

**Review by fredtruman — COMMENTED** [review]
Sorry for the delay, but looking nice! I had a couple questions:

1). Wondering if the naming convention should start with the color first, then light/dark, then the number? My thought is that it currently is a little tough to parse the list like:
Light Gray 2
Light Gray 1
Base Gray
Dark Gray 1
Dark Gray 2

etc... vs:

Gray Dark 2
Gray Dark 1
Gray Base
Gray Light 1
Gray Light 2

Maybe easier to account for the number of grays available?

2). Any thoughts on providing layer styles in the Palette file for each of the colors? Currently there are some legacy layer styles in there. We should either just remove them, or remove them and add new ones to match the palette convention:
Screenshot 2019-05-23 11 59 03

3). I really like the hues and how they work for banners, esp contrast feels great. In trying them out, the one thing that feels slightly off is that the contrast between Light Yellow 2 and Light Yellow 3 feels less than the those for the other colors (i.e. background color for banners vs. their border color):

Screenshot 2019-05-23 12 06 03

Thoughts?

**Comment by DesignerDave** [comment]
1. I buy the thought. What about:
  Gray: Dark 3
  Gray: Dark 2
  Gray: Dark 1
  Gray: Base
  Gray: Light 2
  Gray: Light 2
  Gray: Light 3
2. Layer styles being there is 100% accidental. Will remove.
3. This might be the most difficult. I think it's so light because it needs enough contrast with `Yellow: Dark 2`. I can see if I could accomplish this with value / hue changes while maintaining the contrast pair, but might be stuck with slightly different contrast for yellows vs the other colors. In actual usage, this inconsistency would be near impossible to spot, but I'll do my best.

**Comment by DesignerDave** [comment]
@fredtruman RFAL

Notes:
1. Updated the naming convention. Now it's `Gray: Light 3` rather than `Light Gray 3`.
2. Layer styles are gone!
3. I updated `Yellow: Light 2` to be slightly darker. I'm afraid that this is the furthest we can take it while maintaining 4.5:1 with `Yellow: Dark 2`, but it looks more consistent now.

**Comment by DesignerDave** [comment]
Another update: re-added layer styles (and updated to the current palette and naming).

Realized it would be a mistake to not include fill layer styles (both for use within other library files and by designers). Layer styles automatically stay up-to-date wherever they're used, whereas a palette is not.

I imagine at some point we should create some text styles too, but we can add those in the future. I specifically needed layer styles for the Glyphs library.

**Comment by fredtruman** [comment]
Thanks @DesignerDave !

1). **Should probably fix** Noticing that though it appears the layer styles have the new naming convention, the document swatches did not get the change? See screenshots (do you see the same thing?):
Screenshot 2019-05-28 09 45 54
Screenshot 2019-05-28 09 46 04

2). **Maybe fix?** Nice, thanks for adding the layer styles! I don't think this is possibly currently with Sketch, but wondering if its possible to retain the old ordering at all, where the base is in the middle with lights on top and darks on bottom (or dark on top, lights on bottom - doesn't matter to me really, only point was that I think it makes sense to keep the base in the middle)? If not, I would say leave as is but keep the ordering on the document swatches

3). **Either way, but fine** Ah ok, I didn't know that having `dark 2` and `light 2` meet AA contrast was a goal. If you have good reason for this (can think of an application of those) then cool. I was under the assumption we were only trying to have `dark 3` and `light 3` meet those standards. Defer to your recommendation

**Comment by DesignerDave** [comment]
1. Oops – I swear I went through them all and updated them, so not sure how that update was removed. I'll fix that.
2. I wish, but as much as I tried, the layer styles appear to be alphabetical.
3. I decided to make that a goal to allow for a much wider set of colors that can be used together in an accessible way. I didn't want the palette to be overly restrictive in that way, and we weren't far from it in earlier iterations, so I made sure that the combinations met those standards. The darker `Yellow: Light 2` should now be more consistent with the rest while adhering to those standards.

**Comment by fredtruman** [comment]
RFAL @DesignerDave ? Looking at latest commit:

1. LGTM
2. Figured 😞 
3. 👍 

:shipit:

**Pull request merged**
